CREATE TABLE tb_missoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    dificuldade VARCHAR(255)
);

CREATE TABLE tb_ninjas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    idade INT,
    missoes_id BIGINT,
    CONSTRAINT fk_tb_ninjas_missoes
        FOREIGN KEY (missoes_id)
        REFERENCES tb_missoes(id)
);
